<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'name'               => 'Indofood Sukses Makmur',
                'contact_name'       => 'Budi Santoso',
                'phone'              => '021-5795-8822',
                'email'              => 'partner@indofood.com',
                'website'            => 'https://www.indofood.com',
                'city'               => 'Jakarta',
                'product_categories' => ['Bumbu', 'Mie', 'Tepung', 'Minuman'],
                'business_type'      => 'fnb',
                'rating'             => 4.8,
                'review_count'       => 1243,
                'description'        => 'Supplier produk makanan & minuman terbesar di Indonesia. Tersedia program kemitraan untuk UMKM.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'Bogasari Flour Mills',
                'contact_name'       => 'Siti Rahayu',
                'phone'              => '021-384-5555',
                'email'              => 'distributor@bogasari.com',
                'website'            => 'https://www.bogasari.com',
                'city'               => 'Jakarta',
                'product_categories' => ['Tepung', 'Ragi', 'Bahan Roti'],
                'business_type'      => 'fnb',
                'rating'             => 4.7,
                'review_count'       => 892,
                'description'        => 'Produsen tepung terigu terkemuka. Supplier ideal untuk bisnis bakery, pastry, dan kuliner.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'PT Garudafood Putra Putri Jaya',
                'contact_name'       => 'Ahmad Fauzi',
                'phone'              => '021-5694-8888',
                'email'              => 'b2b@garudafood.com',
                'website'            => 'https://www.garudafood.com',
                'city'               => 'Jakarta',
                'product_categories' => ['Snack', 'Kacang', 'Minuman', 'Permen'],
                'business_type'      => 'fnb',
                'rating'             => 4.5,
                'review_count'       => 567,
                'description'        => 'Produsen camilan & minuman ringan. Cocok untuk bisnis warung, minimarket, dan FnB.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'UD Sumber Segar',
                'contact_name'       => 'Dewi Kusuma',
                'phone'              => '0812-3456-7890',
                'email'              => 'info@sumbersegar.co.id',
                'website'            => null,
                'city'               => 'Bandung',
                'product_categories' => ['Sayuran Segar', 'Buah-buahan', 'Herbal'],
                'business_type'      => 'fnb',
                'rating'             => 4.6,
                'review_count'       => 328,
                'description'        => 'Distributor sayuran dan buah-buahan segar langsung dari petani lokal. Pengiriman harian ke area Jabodetabek & Bandung.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'Kemasan Pro Indonesia',
                'contact_name'       => 'Rizky Pratama',
                'phone'              => '021-7788-1234',
                'email'              => 'sales@kemasanpro.id',
                'website'            => 'https://www.kemasanpro.id',
                'city'               => 'Tangerang',
                'product_categories' => ['Kemasan', 'Plastik', 'Dus', 'Label'],
                'business_type'      => null,
                'rating'             => 4.4,
                'review_count'       => 445,
                'description'        => 'Supplier kemasan produk untuk berbagai jenis bisnis. Custom print logo & desain tersedia dengan MOQ rendah.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'Minyak Goreng Bimoli Distribution',
                'contact_name'       => 'Hendra Wijaya',
                'phone'              => '021-4455-6677',
                'email'              => 'distribusi@bimoli.co.id',
                'website'            => 'https://www.bimoli.co.id',
                'city'               => 'Jakarta',
                'product_categories' => ['Minyak Goreng', 'Lemak Nabati'],
                'business_type'      => 'fnb',
                'rating'             => 4.3,
                'review_count'       => 234,
                'description'        => 'Distributor resmi minyak goreng Bimoli. Harga grosir untuk pembelian minimum 1 karton.',
                'is_verified'        => false,
                'is_active'          => true,
            ],
            [
                'name'               => 'PT Tirta Investama (AQUA)',
                'contact_name'       => 'Maya Sari',
                'phone'              => '021-5299-6000',
                'email'              => 'b2b@aqua.com',
                'website'            => 'https://www.aqua.com',
                'city'               => 'Jakarta',
                'product_categories' => ['Air Mineral', 'Minuman'],
                'business_type'      => 'fnb',
                'rating'             => 4.9,
                'review_count'       => 1567,
                'description'        => 'Distributor air mineral AQUA untuk bisnis restoran, kafe, hotel, dan event.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'Toko Alat Masak Grosir',
                'contact_name'       => 'Joko Susilo',
                'phone'              => '0878-1234-5678',
                'email'              => 'grosir@alatmasak.co.id',
                'website'            => null,
                'city'               => 'Surabaya',
                'product_categories' => ['Peralatan Masak', 'Peralatan Dapur', 'Peralatan Makan'],
                'business_type'      => 'fnb',
                'rating'             => 4.2,
                'review_count'       => 189,
                'description'        => 'Grosir peralatan dapur & makan untuk restoran, kafe, dan katering. Harga terjangkau dengan kualitas terjamin.',
                'is_verified'        => false,
                'is_active'          => true,
            ],
            [
                'name'               => 'Retail Packaging Solutions',
                'contact_name'       => 'Linda Priyanto',
                'phone'              => '021-6677-8899',
                'email'              => 'info@retailpack.id',
                'website'            => 'https://www.retailpack.id',
                'city'               => 'Bekasi',
                'product_categories' => ['Kemasan Retail', 'Hangtag', 'Label Barcode'],
                'business_type'      => 'retail',
                'rating'             => 4.5,
                'review_count'       => 312,
                'description'        => 'Solusi kemasan untuk bisnis retail fashion dan produk konsumer. Custom branding dan desain tersedia.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
            [
                'name'               => 'Grosir Bahan Baku Kopi Nusantara',
                'contact_name'       => 'Arief Rahman',
                'phone'              => '0821-9876-5432',
                'email'              => 'kopi@nusantara.co.id',
                'website'            => null,
                'city'               => 'Medan',
                'product_categories' => ['Kopi', 'Teh', 'Bahan Minuman'],
                'business_type'      => 'fnb',
                'rating'             => 4.7,
                'review_count'       => 421,
                'description'        => 'Supplier biji kopi premium langsung dari petani Sumatera, Aceh, dan Toraja. Tersedia dalam berbagai grade.',
                'is_verified'        => true,
                'is_active'          => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
